name: Tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  run_unit_test:
    runs-on: ubuntu-latest 
    steps: 
        - uses: actions/checkout@v4
        - uses: mamba-org/setup-micromamba@v2
          with: 
            environment-file: environment.yml
            init-shell: bash
        - run: |
            echo "hooking"
            eval "$(micromamba shell hook --shell bash)"
            echo "Post eval"
            micromamba activate swe4s
            echo "Post activate"
            curl -L "https://docs.google.com/uc?export=download&id=1Wytf3ryf9EtOwaloms8HEzLG0yjtRqxr" -o Agrofood_co2_emission.csv
            echo "Post file download"
            python test/test_my_utils.py
            echo "Done"
  run_func_test:
    runs-on: ubuntu-latest 
    steps: 
        - uses: actions/checkout@v4
        - run: bash test/test_print_fires.sh
          shell: bash -l {0}
  run_style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with: 
          environment-file: environment.yml
          init-shell: bash
      - run: pycodestyle $(git ls-files "*.py")
        shell: bash -l {0}
